
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkeceanqsbkchxakmuet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrZWNlYW5xc2JrY2h4YWttdWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzA2MTMsImV4cCI6MjA1ODc0NjYxM30.MSAT0K8II_x4pEqVC3zgIL6_PfqcMJsM1FUGUllworU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: globalThis.localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
